import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../state/app_state.dart';
import '../../theme/app_theme.dart';
import '../../widgets/app_button.dart';
import '../../widgets/app_card.dart';

const _kSupportEmail = 'support@mediconnectai.app';

class _Faq {
  const _Faq(this.question, this.answer);
  final String question;
  final String answer;
}

const _faqs = [
  _Faq(
    'How do I sign a prescription?',
    'Open the Prescription tab during a consultation, add at least one named medicine, then tap "Sign Prescription". '
        'You\'ll be asked to confirm — signing is irreversible, so double-check the medicines and diagnosis first. '
        'Once signed, the PDF is generated server-side and the appointment is marked complete.',
  ),
  _Faq(
    'How is my digital signature stored?',
    'Your signature is applied server-side at the moment you approve a prescription — it is never stored or '
        'transmitted unlocked from this device. You can review or reset it from Profile → Security & Privacy.',
  ),
  _Faq(
    'Why does a screen show "offline" data?',
    'If the app can\'t reach the server, it falls back to the last data it successfully synced rather than showing '
        'a blank screen. A banner tells you when this happens and roughly how stale the data is. Actions you take '
        'while offline are queued and retried once you\'re back online.',
  ),
  _Faq(
    'What does the "AI Scribe" / "AI Suggestion" label mean?',
    'Anything generated by the AI service is visibly marked — in lists, detail views, and exported PDFs — so it\'s '
        'never mistaken for something you personally verified. You can always edit AI-suggested content before it '
        'becomes part of the official record.',
  ),
  _Faq(
    'A patient is marked "no-show" by mistake — can I undo it?',
    'From the Queue tab, no-show is a terminal status for that appointment, matching how the backend models the '
        'appointment lifecycle. If it was a genuine mistake, add the patient again as a walk-in from Queue or '
        'Appointments so they aren\'t lost from today\'s roster.',
  ),
];

/// Real, specific FAQ content plus a working "Contact Support" action —
/// replaces the old placeholder that only echoed its own item titles back
/// with no actual answers.
class HelpSupportScreen extends StatelessWidget {
  const HelpSupportScreen({super.key});

  Future<void> _contactSupport(BuildContext context, AppState app) async {
    final uri = Uri(
      scheme: 'mailto',
      path: _kSupportEmail,
      query: 'subject=${Uri.encodeComponent('MediConnectAI Doctor App — Support Request')}'
          '&body=${Uri.encodeComponent('Describe the issue here.\n\n— ${app.doctorDisplayName}')}',
    );
    final launched = await launchUrl(uri);
    if (!context.mounted) return;
    if (!launched) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No mail app is configured on this device.'), backgroundColor: AppColors.red600),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final app = context.watch<AppState>();
    return Scaffold(
      backgroundColor: AppColors.blue50,
      appBar: AppBar(
        backgroundColor: AppColors.blue50,
        elevation: 0,
        leading: IconButton(icon: const Icon(Icons.arrow_back, color: AppColors.ink900), onPressed: () => Navigator.pop(context)),
        title: Text('Help & Support', style: AppText.display(size: 16)),
        centerTitle: true,
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          Text('FREQUENTLY ASKED QUESTIONS', style: AppText.mono(size: 10, color: AppColors.ink600, weight: FontWeight.bold)),
          const SizedBox(height: 10),
          AppCard(
            padding: EdgeInsets.zero,
            child: Column(
              children: _faqs.asMap().entries.map((entry) {
                final i = entry.key;
                final f = entry.value;
                return Container(
                  decoration: BoxDecoration(
                    border: Border(bottom: BorderSide(color: i == _faqs.length - 1 ? Colors.transparent : AppColors.lineSoft)),
                  ),
                  child: ExpansionTile(
                    title: Text(f.question, style: AppText.body(size: 13, weight: FontWeight.w700)),
                    childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
                    expandedCrossAxisAlignment: CrossAxisAlignment.start,
                    children: [Text(f.answer, style: AppText.body(size: 12.5, color: AppColors.ink600).copyWith(height: 1.4))],
                  ),
                ).animate(delay: (i * 40).ms).fadeIn(duration: 220.ms).slideY(begin: 0.06, end: 0, curve: Curves.easeOut);
              }).toList(),
            ),
          ),
          const SizedBox(height: 20),
          AppButton(label: 'Contact Support', icon: const Icon(Icons.mail_outline, size: 16), variant: AppButtonVariant.ghost, block: true, onPressed: () => _contactSupport(context, app))
              .animate(delay: (_faqs.length * 40 + 60).ms)
              .fadeIn(duration: 240.ms)
              .slideY(begin: 0.06, end: 0, curve: Curves.easeOut),
        ],
      ),
    );
  }
}
